sudo: false
language: erlang
otp_release:
  - 17.5
addons:
  apt:
    packages:
      - xsltproc
env:
  - BUILD_DIR=$HOME/rabbitmq-public-umbrella RABBIT_TAG=v3_5_3 BUILD_VERSION=v3.5.x
before_install:
  - "$TRAVIS_BUILD_DIR/travis-umbrella-setup.sh"
script: cd $BUILD_DIR/pgsql-listen-exchange && make test
after_script:
  - rm -rf $BUILD_DIR/pgsql-listen-exchange
before_deploy:
  - cd $BUILD_DIR/pgsql-listen-exchange
  - VERSION=$TRAVIS_TAG make
  - cd $BUILD_DIR/pgsql-listen-exchange/dist && zip pgsql-listen-exchange-${TRAVIS_TAG}.zip epgsql*ez pgsql*ez
cache:
  apt: true
  directories:
    - $BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: tqI4Ted0Qp68oHqQ/hXvvsrR0lOB5c6eLLOuFb/HlAJMNKMs6yPw5Z4YY1ldVZsOhr5V7yzkb3yKta0PFXgNIaLwA7vsq9nzgF4cbxLScyzlcb7Sx/7Avr16AOQxiz13NCKDLi64AE+1rUCqvJfAtexQ98Ls/zzzBnBI81t/yOs=
  file: $BUILD_DIR/pgsql-listen-exchange/dist/pgsql-listen-exchange-${TRAVIS_TAG}.zip
  on:
    tags: true
    repo: aweber/pgsql-listen-exchange
