version: '3.3'
services:

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672
      - 15672
    container_name: rabbitmq-server
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

