name: Build
on:
  push:
    branches-ignore: ["*"]
    tags: ["*"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'gmr/pgsql-listen-exchange'
    container: ghcr.io/gmr/erlang-elixir:21.3-1.10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build artifact
        run: |-
          apt-get update
          apt-get install -y rsync
          make dist
          tar cvfz pgsql-listen-exchange-${GITHUB_REF:10}.tar.gz plugins/epgsql-* plugins/pgsql_listen_exchange-${GITHUB_REF:10}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${GITHUB_REF:10}
          release_name: v${GITHUB_REF:10}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pgsql-listen-exchange-${GITHUB_REF:10}.tar.gz
          asset_name: pgsql-listen-exchange-${GITHUB_REF:10}.tar.gz
          asset_content_type: application/x-tgz
