name: Testing
on:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "/usr/bin/pg_isready"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to ghcr.io
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u gmr --password-stdin

      - name: Run tests
        uses: docker://ghcr.io/gmr/erlang-elixir:21.3-1.10
        run: make tests
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: password
